# Stage 1: Build React App
FROM node:latest AS build

WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY vite-project/package*.json ./

# Install dependencies
RUN npm install

# Copy all the app files to the working directory
COPY vite-project .

# Build the React app
RUN npm run build

# Stage 2: Serve React App using NGINX
FROM nginx:alpine

# Copy the built React app from the build stage to NGINX's default public directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80