version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "7777:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "7000:5186"